name = "synthetix-governance-satellite"
description = "On-chain voting for synthetix councils - Logic for satellite chains"
version = "<%= package.version %>"
include = ["./tomls/proxy-base.toml", "./tomls/council-token.toml"]

[setting.initial_council_member]
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.initial_epoch_index]
defaultValue = "0"

[setting.initial_epoch_start_date]
defaultValue = "0"

[setting.initial_nomination_period_start_date]
defaultValue = "0"

[setting.initial_voting_period_start_date]
defaultValue = "0"

[setting.wormhole_delivery_provider]
defaultValue = "0x28D8F1Be96f97C1387e94A53e00eCcFb4E75175a"

[setting.initial_epoch_end_date]
defaultValue = "0"

[contract.AssociatedSystemsModule]
artifact = "contracts/modules/core/AssociatedSystemsModule.sol:AssociatedSystemsModule"

[contract.CrossChainModule]
artifact = "contracts/modules/core/CrossChainModule.sol:CrossChainModule"

[contract.ElectionModuleSatellite]
artifact = "contracts/modules/core/ElectionModuleSatellite.sol:ElectionModuleSatellite"

[contract.SnapshotVotePowerModule]
artifact = "contracts/modules/core/SnapshotVotePowerModule.sol:SnapshotVotePowerModule"

[contract.CcipReceiverModule]
artifact = "contracts/modules/core/CcipReceiverModule.sol:CcipReceiverModule"

[contract.WormholeMock]
artifact = "contracts/mocks/WormholeMock.sol:WormholeMock"
args = ["10005"]

[contract.WormholeRelayerMock]
artifact = "contracts/mocks/WormholeRelayerMock.sol:WormholeRelayerMock"
args = ["<%= contracts.WormholeMock.address %>"]

[router.CoreRouter]
contracts = [
    "AssociatedSystemsModule",
    "CrossChainModule",
    "ElectionModuleSatellite",
    "SnapshotVotePowerModule",
    "InitialModuleBundle",
    "CcipReceiverModule"
]

[invoke.upgrade_core_proxy]
target = ["InitialProxy"]
from = "<%= settings.owner %>"
func = "upgradeTo"
args = ["<%= contracts.CoreRouter.address %>"]
factory.GovernanceProxy.abiOf = ["CoreRouter"]
factory.GovernanceProxy.event = "Upgraded"
factory.GovernanceProxy.arg = 0
factory.GovernanceProxy.highlight = true

[invoke.init_election_module]
target = ["GovernanceProxy"]
func = "initElectionModuleSatellite(uint256,uint64,uint64,uint64,uint64,address,address,address,address[])"
args = [
    "<%= settings.initial_epoch_index %>",
    "<%= settings.initial_epoch_start_date %>",
    "<%= settings.initial_nomination_period_start_date %>",
    "<%= settings.initial_voting_period_start_date %>",
    "<%= settings.initial_epoch_end_date %>",
    "<%= settings.wormhole_delivery_provider %>",
    "<%= settings.wormhole_core %>",
    "<%= settings.wormhole_relayer %>",
    ["<%= settings.initial_council_member %>"],
]
from = "<%= settings.owner %>"
