name = "synthetix-governance"
version = "<%= package.version %>-test-sat"
include = ["cannonfile.satellite.toml"]

[contract.SnapshotRecordMock]
artifact = "contracts/mocks/SnapshotRecordMock.sol:SnapshotRecordMock"
