name = "synthetix-governance"
version = "<%= package.version %>-test-sat"
include = ["cannonfile.avalanche-fuji-satelite.toml", "tomls/ccip.test.toml"]

[contract.SnapshotRecordMock]
artifact = "contracts/mocks/SnapshotRecordMock.sol:SnapshotRecordMock"
